// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service.proto

package advancedpb

import (
	_ "github.com/yurasolovjov/protodefault/proto/defaults/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogLevel определяет уровень логирования.
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

// DatabaseConfig содержит настройки подключения к базе данных.
type DatabaseConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Database      string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	MaxOpenConns  int32                  `protobuf:"varint,4,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	MaxIdleConns  int32                  `protobuf:"varint,5,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseConfig) Reset() {
	*x = DatabaseConfig{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseConfig) ProtoMessage() {}

func (x *DatabaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseConfig.ProtoReflect.Descriptor instead.
func (*DatabaseConfig) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *DatabaseConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DatabaseConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DatabaseConfig) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DatabaseConfig) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *DatabaseConfig) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

// CacheConfig содержит настройки кэширования.
type CacheConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	MaxSizeMb     int32                  `protobuf:"varint,3,opt,name=max_size_mb,json=maxSizeMb,proto3" json:"max_size_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheConfig) Reset() {
	*x = CacheConfig{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheConfig) ProtoMessage() {}

func (x *CacheConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheConfig.ProtoReflect.Descriptor instead.
func (*CacheConfig) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *CacheConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CacheConfig) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *CacheConfig) GetMaxSizeMb() int32 {
	if x != nil {
		return x.MaxSizeMb
	}
	return 0
}

// ServiceConfig демонстрирует продвинутое использование default_value:
// - Вложенные сообщения
// - Enum
// - Repeated поля
// - Map поля
// - Well-known types (Duration)
type ServiceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Имя сервиса.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Уровень логирования. По умолчанию INFO.
	LogLevel LogLevel `protobuf:"varint,2,opt,name=log_level,json=logLevel,proto3,enum=example.advanced.v1.LogLevel" json:"log_level,omitempty"`
	// Настройки базы данных (вложенное сообщение).
	Database *DatabaseConfig `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	// Настройки кэша (вложенное сообщение).
	Cache *CacheConfig `protobuf:"bytes,4,opt,name=cache,proto3" json:"cache,omitempty"`
	// Разрешённые origins для CORS.
	AllowedOrigins []string `protobuf:"bytes,5,rep,name=allowed_origins,json=allowedOrigins,proto3" json:"allowed_origins,omitempty"`
	// Интервалы повторных попыток в секундах.
	RetryIntervals []int32 `protobuf:"varint,6,rep,packed,name=retry_intervals,json=retryIntervals,proto3" json:"retry_intervals,omitempty"`
	// Лимиты по ресурсам.
	RateLimits map[string]int32 `protobuf:"bytes,7,rep,name=rate_limits,json=rateLimits,proto3" json:"rate_limits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Таймаут запроса.
	RequestTimeout *durationpb.Duration `protobuf:"bytes,8,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	// Таймаут graceful shutdown.
	ShutdownTimeout *durationpb.Duration `protobuf:"bytes,9,opt,name=shutdown_timeout,json=shutdownTimeout,proto3" json:"shutdown_timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceConfig) GetLogLevel() LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *ServiceConfig) GetDatabase() *DatabaseConfig {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *ServiceConfig) GetCache() *CacheConfig {
	if x != nil {
		return x.Cache
	}
	return nil
}

func (x *ServiceConfig) GetAllowedOrigins() []string {
	if x != nil {
		return x.AllowedOrigins
	}
	return nil
}

func (x *ServiceConfig) GetRetryIntervals() []int32 {
	if x != nil {
		return x.RetryIntervals
	}
	return nil
}

func (x *ServiceConfig) GetRateLimits() map[string]int32 {
	if x != nil {
		return x.RateLimits
	}
	return nil
}

func (x *ServiceConfig) GetRequestTimeout() *durationpb.Duration {
	if x != nil {
		return x.RequestTimeout
	}
	return nil
}

func (x *ServiceConfig) GetShutdownTimeout() *durationpb.Duration {
	if x != nil {
		return x.ShutdownTimeout
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x13example.advanced.v1\x1a\x19defaults/v1/options.proto\x1a\x1egoogle/protobuf/duration.proto\"\xd4\x01\n" +
	"\x0eDatabaseConfig\x12!\n" +
	"\x04host\x18\x01 \x01(\tB\r\x8a\xb5\x18\tlocalhostR\x04host\x12\x1c\n" +
	"\x04port\x18\x02 \x01(\x05B\b\x8a\xb5\x18\x045432R\x04port\x12&\n" +
	"\bdatabase\x18\x03 \x01(\tB\n" +
	"\x8a\xb5\x18\x06app_dbR\bdatabase\x12,\n" +
	"\x0emax_open_conns\x18\x04 \x01(\x05B\x06\x8a\xb5\x18\x0225R\fmaxOpenConns\x12+\n" +
	"\x0emax_idle_conns\x18\x05 \x01(\x05B\x05\x8a\xb5\x18\x015R\fmaxIdleConns\"\x91\x01\n" +
	"\vCacheConfig\x12\"\n" +
	"\aenabled\x18\x01 \x01(\bB\b\x8a\xb5\x18\x04trueR\aenabled\x125\n" +
	"\x03ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\b\x8a\xb5\x18\x04300sR\x03ttl\x12'\n" +
	"\vmax_size_mb\x18\x03 \x01(\x05B\a\x8a\xb5\x18\x03256R\tmaxSizeMb\"\xfe\x05\n" +
	"\rServiceConfig\x12\"\n" +
	"\x04name\x18\x01 \x01(\tB\x0e\x8a\xb5\x18\n" +
	"my-serviceR\x04name\x12N\n" +
	"\tlog_level\x18\x02 \x01(\x0e2\x1d.example.advanced.v1.LogLevelB\x12\x8a\xb5\x18\x0eLOG_LEVEL_INFOR\blogLevel\x12?\n" +
	"\bdatabase\x18\x03 \x01(\v2#.example.advanced.v1.DatabaseConfigR\bdatabase\x126\n" +
	"\x05cache\x18\x04 \x01(\v2 .example.advanced.v1.CacheConfigR\x05cache\x12_\n" +
	"\x0fallowed_origins\x18\x05 \x03(\tB6\x8a\xb5\x182[\"http://localhost:3000\", \"http://localhost:8080\"]R\x0eallowedOrigins\x12>\n" +
	"\x0fretry_intervals\x18\x06 \x03(\x05B\x15\x8a\xb5\x18\x11[1, 2, 5, 10, 30]R\x0eretryIntervals\x12\x83\x01\n" +
	"\vrate_limits\x18\a \x03(\v22.example.advanced.v1.ServiceConfig.RateLimitsEntryB.\x8a\xb5\x18*{\"requests_per_second\": 100, \"burst\": 200}R\n" +
	"rateLimits\x12K\n" +
	"\x0frequest_timeout\x18\b \x01(\v2\x19.google.protobuf.DurationB\a\x8a\xb5\x18\x0330sR\x0erequestTimeout\x12M\n" +
	"\x10shutdown_timeout\x18\t \x01(\v2\x19.google.protobuf.DurationB\a\x8a\xb5\x18\x0315sR\x0fshutdownTimeout\x1a=\n" +
	"\x0fRateLimitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01*w\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x04BHZFgithub.com/yurasolovjov/protodefault/example/advanced/proto;advancedpbb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_proto_goTypes = []any{
	(LogLevel)(0),               // 0: example.advanced.v1.LogLevel
	(*DatabaseConfig)(nil),      // 1: example.advanced.v1.DatabaseConfig
	(*CacheConfig)(nil),         // 2: example.advanced.v1.CacheConfig
	(*ServiceConfig)(nil),       // 3: example.advanced.v1.ServiceConfig
	nil,                         // 4: example.advanced.v1.ServiceConfig.RateLimitsEntry
	(*durationpb.Duration)(nil), // 5: google.protobuf.Duration
}
var file_service_proto_depIdxs = []int32{
	5, // 0: example.advanced.v1.CacheConfig.ttl:type_name -> google.protobuf.Duration
	0, // 1: example.advanced.v1.ServiceConfig.log_level:type_name -> example.advanced.v1.LogLevel
	1, // 2: example.advanced.v1.ServiceConfig.database:type_name -> example.advanced.v1.DatabaseConfig
	2, // 3: example.advanced.v1.ServiceConfig.cache:type_name -> example.advanced.v1.CacheConfig
	4, // 4: example.advanced.v1.ServiceConfig.rate_limits:type_name -> example.advanced.v1.ServiceConfig.RateLimitsEntry
	5, // 5: example.advanced.v1.ServiceConfig.request_timeout:type_name -> google.protobuf.Duration
	5, // 6: example.advanced.v1.ServiceConfig.shutdown_timeout:type_name -> google.protobuf.Duration
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
