// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: test/v1/test_messages.proto

package testv1

import (
	_ "github.com/yurasolovjov/protodefault/proto/defaults/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_test_v1_test_messages_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_test_v1_test_messages_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_test_v1_test_messages_proto_rawDescGZIP(), []int{0}
}

type FeatureFlag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureFlag) Reset() {
	*x = FeatureFlag{}
	mi := &file_test_v1_test_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureFlag) ProtoMessage() {}

func (x *FeatureFlag) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_test_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureFlag.ProtoReflect.Descriptor instead.
func (*FeatureFlag) Descriptor() ([]byte, []int) {
	return file_test_v1_test_messages_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureFlag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeatureFlag) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type TestMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scalars
	StrField    string  `protobuf:"bytes,1,opt,name=str_field,json=strField,proto3" json:"str_field,omitempty"`
	Int32Field  int32   `protobuf:"varint,2,opt,name=int32_field,json=int32Field,proto3" json:"int32_field,omitempty"`
	Uint64Field uint64  `protobuf:"varint,3,opt,name=uint64_field,json=uint64Field,proto3" json:"uint64_field,omitempty"`
	DoubleField float64 `protobuf:"fixed64,4,opt,name=double_field,json=doubleField,proto3" json:"double_field,omitempty"`
	BoolField   bool    `protobuf:"varint,5,opt,name=bool_field,json=boolField,proto3" json:"bool_field,omitempty"`
	BytesField  []byte  `protobuf:"bytes,6,opt,name=bytes_field,json=bytesField,proto3" json:"bytes_field,omitempty"`
	// Optional scalars (proto3 presence)
	OptStrField   *string `protobuf:"bytes,7,opt,name=opt_str_field,json=optStrField,proto3,oneof" json:"opt_str_field,omitempty"`
	OptInt32Field *int32  `protobuf:"varint,8,opt,name=opt_int32_field,json=optInt32Field,proto3,oneof" json:"opt_int32_field,omitempty"`
	// Enum
	LevelByName   LogLevel `protobuf:"varint,9,opt,name=level_by_name,json=levelByName,proto3,enum=test.v1.LogLevel" json:"level_by_name,omitempty"`
	LevelByNumber LogLevel `protobuf:"varint,10,opt,name=level_by_number,json=levelByNumber,proto3,enum=test.v1.LogLevel" json:"level_by_number,omitempty"`
	// Nested message
	Feature *FeatureFlag `protobuf:"bytes,11,opt,name=feature,proto3" json:"feature,omitempty"`
	// Repeated
	Tags     []string       `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	Features []*FeatureFlag `protobuf:"bytes,13,rep,name=features,proto3" json:"features,omitempty"`
	// Map
	StringToInt map[string]int32        `protobuf:"bytes,14,rep,name=string_to_int,json=stringToInt,proto3" json:"string_to_int,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StringToMsg map[string]*FeatureFlag `protobuf:"bytes,15,rep,name=string_to_msg,json=stringToMsg,proto3" json:"string_to_msg,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Oneof
	//
	// Types that are valid to be assigned to Choice:
	//
	//	*TestMessage_ChoiceStr
	//	*TestMessage_ChoiceInt
	Choice isTestMessage_Choice `protobuf_oneof:"choice"`
	// Well-known types
	Duration      *durationpb.Duration   `protobuf:"bytes,18,opt,name=duration,proto3" json:"duration,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	StructField   *structpb.Struct       `protobuf:"bytes,20,opt,name=struct_field,json=structField,proto3" json:"struct_field,omitempty"`
	ListField     *structpb.ListValue    `protobuf:"bytes,21,opt,name=list_field,json=listField,proto3" json:"list_field,omitempty"`
	ValueField    *structpb.Value        `protobuf:"bytes,22,opt,name=value_field,json=valueField,proto3" json:"value_field,omitempty"`
	MaskField     *fieldmaskpb.FieldMask `protobuf:"bytes,23,opt,name=mask_field,json=maskField,proto3" json:"mask_field,omitempty"`
	BoolWrapper   *wrapperspb.BoolValue  `protobuf:"bytes,24,opt,name=bool_wrapper,json=boolWrapper,proto3" json:"bool_wrapper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_test_v1_test_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_test_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_test_v1_test_messages_proto_rawDescGZIP(), []int{1}
}

func (x *TestMessage) GetStrField() string {
	if x != nil {
		return x.StrField
	}
	return ""
}

func (x *TestMessage) GetInt32Field() int32 {
	if x != nil {
		return x.Int32Field
	}
	return 0
}

func (x *TestMessage) GetUint64Field() uint64 {
	if x != nil {
		return x.Uint64Field
	}
	return 0
}

func (x *TestMessage) GetDoubleField() float64 {
	if x != nil {
		return x.DoubleField
	}
	return 0
}

func (x *TestMessage) GetBoolField() bool {
	if x != nil {
		return x.BoolField
	}
	return false
}

func (x *TestMessage) GetBytesField() []byte {
	if x != nil {
		return x.BytesField
	}
	return nil
}

func (x *TestMessage) GetOptStrField() string {
	if x != nil && x.OptStrField != nil {
		return *x.OptStrField
	}
	return ""
}

func (x *TestMessage) GetOptInt32Field() int32 {
	if x != nil && x.OptInt32Field != nil {
		return *x.OptInt32Field
	}
	return 0
}

func (x *TestMessage) GetLevelByName() LogLevel {
	if x != nil {
		return x.LevelByName
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *TestMessage) GetLevelByNumber() LogLevel {
	if x != nil {
		return x.LevelByNumber
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *TestMessage) GetFeature() *FeatureFlag {
	if x != nil {
		return x.Feature
	}
	return nil
}

func (x *TestMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TestMessage) GetFeatures() []*FeatureFlag {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *TestMessage) GetStringToInt() map[string]int32 {
	if x != nil {
		return x.StringToInt
	}
	return nil
}

func (x *TestMessage) GetStringToMsg() map[string]*FeatureFlag {
	if x != nil {
		return x.StringToMsg
	}
	return nil
}

func (x *TestMessage) GetChoice() isTestMessage_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *TestMessage) GetChoiceStr() string {
	if x != nil {
		if x, ok := x.Choice.(*TestMessage_ChoiceStr); ok {
			return x.ChoiceStr
		}
	}
	return ""
}

func (x *TestMessage) GetChoiceInt() int32 {
	if x != nil {
		if x, ok := x.Choice.(*TestMessage_ChoiceInt); ok {
			return x.ChoiceInt
		}
	}
	return 0
}

func (x *TestMessage) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *TestMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TestMessage) GetStructField() *structpb.Struct {
	if x != nil {
		return x.StructField
	}
	return nil
}

func (x *TestMessage) GetListField() *structpb.ListValue {
	if x != nil {
		return x.ListField
	}
	return nil
}

func (x *TestMessage) GetValueField() *structpb.Value {
	if x != nil {
		return x.ValueField
	}
	return nil
}

func (x *TestMessage) GetMaskField() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.MaskField
	}
	return nil
}

func (x *TestMessage) GetBoolWrapper() *wrapperspb.BoolValue {
	if x != nil {
		return x.BoolWrapper
	}
	return nil
}

type isTestMessage_Choice interface {
	isTestMessage_Choice()
}

type TestMessage_ChoiceStr struct {
	ChoiceStr string `protobuf:"bytes,16,opt,name=choice_str,json=choiceStr,proto3,oneof"`
}

type TestMessage_ChoiceInt struct {
	ChoiceInt int32 `protobuf:"varint,17,opt,name=choice_int,json=choiceInt,proto3,oneof"`
}

func (*TestMessage_ChoiceStr) isTestMessage_Choice() {}

func (*TestMessage_ChoiceInt) isTestMessage_Choice() {}

type OneofConflict struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Conflict:
	//
	//	*OneofConflict_A
	//	*OneofConflict_B
	Conflict      isOneofConflict_Conflict `protobuf_oneof:"conflict"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofConflict) Reset() {
	*x = OneofConflict{}
	mi := &file_test_v1_test_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofConflict) ProtoMessage() {}

func (x *OneofConflict) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_test_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofConflict.ProtoReflect.Descriptor instead.
func (*OneofConflict) Descriptor() ([]byte, []int) {
	return file_test_v1_test_messages_proto_rawDescGZIP(), []int{2}
}

func (x *OneofConflict) GetConflict() isOneofConflict_Conflict {
	if x != nil {
		return x.Conflict
	}
	return nil
}

func (x *OneofConflict) GetA() string {
	if x != nil {
		if x, ok := x.Conflict.(*OneofConflict_A); ok {
			return x.A
		}
	}
	return ""
}

func (x *OneofConflict) GetB() string {
	if x != nil {
		if x, ok := x.Conflict.(*OneofConflict_B); ok {
			return x.B
		}
	}
	return ""
}

type isOneofConflict_Conflict interface {
	isOneofConflict_Conflict()
}

type OneofConflict_A struct {
	A string `protobuf:"bytes,1,opt,name=a,proto3,oneof"`
}

type OneofConflict_B struct {
	B string `protobuf:"bytes,2,opt,name=b,proto3,oneof"`
}

func (*OneofConflict_A) isOneofConflict_Conflict() {}

func (*OneofConflict_B) isOneofConflict_Conflict() {}

type RecursiveA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *RecursiveB            `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecursiveA) Reset() {
	*x = RecursiveA{}
	mi := &file_test_v1_test_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecursiveA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecursiveA) ProtoMessage() {}

func (x *RecursiveA) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_test_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecursiveA.ProtoReflect.Descriptor instead.
func (*RecursiveA) Descriptor() ([]byte, []int) {
	return file_test_v1_test_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RecursiveA) GetB() *RecursiveB {
	if x != nil {
		return x.B
	}
	return nil
}

type RecursiveB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *RecursiveA            `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecursiveB) Reset() {
	*x = RecursiveB{}
	mi := &file_test_v1_test_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecursiveB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecursiveB) ProtoMessage() {}

func (x *RecursiveB) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_test_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecursiveB.ProtoReflect.Descriptor instead.
func (*RecursiveB) Descriptor() ([]byte, []int) {
	return file_test_v1_test_messages_proto_rawDescGZIP(), []int{4}
}

func (x *RecursiveB) GetA() *RecursiveA {
	if x != nil {
		return x.A
	}
	return nil
}

var File_test_v1_test_messages_proto protoreflect.FileDescriptor

const file_test_v1_test_messages_proto_rawDesc = "" +
	"\n" +
	"\x1btest/v1/test_messages.proto\x12\atest.v1\x1a\x19defaults/v1/options.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a google/protobuf/field_mask.proto\"R\n" +
	"\vFeatureFlag\x12\x1f\n" +
	"\x04name\x18\x01 \x01(\tB\v\x8a\xb5\x18\aunknownR\x04name\x12\"\n" +
	"\aenabled\x18\x02 \x01(\bB\b\x8a\xb5\x18\x04trueR\aenabled\"\xc0\r\n" +
	"\vTestMessage\x12/\n" +
	"\tstr_field\x18\x01 \x01(\tB\x12\x8a\xb5\x18\x0edefault stringR\bstrField\x12'\n" +
	"\vint32_field\x18\x02 \x01(\x05B\x06\x8a\xb5\x18\x0242R\n" +
	"int32Field\x12-\n" +
	"\fuint64_field\x18\x03 \x01(\x04B\n" +
	"\x8a\xb5\x18\x06100500R\vuint64Field\x12+\n" +
	"\fdouble_field\x18\x04 \x01(\x01B\b\x8a\xb5\x18\x043.14R\vdoubleField\x12'\n" +
	"\n" +
	"bool_field\x18\x05 \x01(\bB\b\x8a\xb5\x18\x04trueR\tboolField\x12*\n" +
	"\vbytes_field\x18\x06 \x01(\fB\t\x8a\xb5\x18\x05helloR\n" +
	"bytesField\x12=\n" +
	"\ropt_str_field\x18\a \x01(\tB\x14\x8a\xb5\x18\x10optional defaultH\x01R\voptStrField\x88\x01\x01\x123\n" +
	"\x0fopt_int32_field\x18\b \x01(\x05B\x06\x8a\xb5\x18\x02-1H\x02R\roptInt32Field\x88\x01\x01\x12I\n" +
	"\rlevel_by_name\x18\t \x01(\x0e2\x11.test.v1.LogLevelB\x12\x8a\xb5\x18\x0eLOG_LEVEL_INFOR\vlevelByName\x12@\n" +
	"\x0flevel_by_number\x18\n" +
	" \x01(\x0e2\x11.test.v1.LogLevelB\x05\x8a\xb5\x18\x013R\rlevelByNumber\x12.\n" +
	"\afeature\x18\v \x01(\v2\x14.test.v1.FeatureFlagR\afeature\x12(\n" +
	"\x04tags\x18\f \x03(\tB\x14\x8a\xb5\x18\x10[\"tag1\", \"tag2\"]R\x04tags\x12Z\n" +
	"\bfeatures\x18\r \x03(\v2\x14.test.v1.FeatureFlagB(\x8a\xb5\x18$[{\"name\": \"feat1\", \"enabled\": true}]R\bfeatures\x12g\n" +
	"\rstring_to_int\x18\x0e \x03(\v2%.test.v1.TestMessage.StringToIntEntryB\x1c\x8a\xb5\x18\x18{\"key1\": 10, \"key2\": 20}R\vstringToInt\x12h\n" +
	"\rstring_to_msg\x18\x0f \x03(\v2%.test.v1.TestMessage.StringToMsgEntryB\x1d\x8a\xb5\x18\x19{\"x\": {\"enabled\": false}}R\vstringToMsg\x12+\n" +
	"\n" +
	"choice_str\x18\x10 \x01(\tB\n" +
	"\x8a\xb5\x18\x06chosenH\x00R\tchoiceStr\x12\x1f\n" +
	"\n" +
	"choice_int\x18\x11 \x01(\x05H\x00R\tchoiceInt\x12>\n" +
	"\bduration\x18\x12 \x01(\v2\x19.google.protobuf.DurationB\a\x8a\xb5\x18\x0315sR\bduration\x12R\n" +
	"\ttimestamp\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampB\x18\x8a\xb5\x18\x142026-01-01T00:00:00ZR\ttimestamp\x12N\n" +
	"\fstruct_field\x18\x14 \x01(\v2\x17.google.protobuf.StructB\x12\x8a\xb5\x18\x0e{\"key\": \"val\"}R\vstructField\x12I\n" +
	"\n" +
	"list_field\x18\x15 \x01(\v2\x1a.google.protobuf.ListValueB\x0e\x8a\xb5\x18\n" +
	"[1, \"two\"]R\tlistField\x12H\n" +
	"\vvalue_field\x18\x16 \x01(\v2\x16.google.protobuf.ValueB\x0f\x8a\xb5\x18\v\"any value\"R\n" +
	"valueField\x12F\n" +
	"\n" +
	"mask_field\x18\x17 \x01(\v2\x1a.google.protobuf.FieldMaskB\v\x8a\xb5\x18\aa.b,c.dR\tmaskField\x12G\n" +
	"\fbool_wrapper\x18\x18 \x01(\v2\x1a.google.protobuf.BoolValueB\b\x8a\xb5\x18\x04trueR\vboolWrapper\x1a>\n" +
	"\x10StringToIntEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aT\n" +
	"\x10StringToMsgEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.test.v1.FeatureFlagR\x05value:\x028\x01B\b\n" +
	"\x06choiceB\x10\n" +
	"\x0e_opt_str_fieldB\x12\n" +
	"\x10_opt_int32_field\"I\n" +
	"\rOneofConflict\x12\x15\n" +
	"\x01a\x18\x01 \x01(\tB\x05\x8a\xb5\x18\x01aH\x00R\x01a\x12\x15\n" +
	"\x01b\x18\x02 \x01(\tB\x05\x8a\xb5\x18\x01bH\x00R\x01bB\n" +
	"\n" +
	"\bconflict\"/\n" +
	"\n" +
	"RecursiveA\x12!\n" +
	"\x01b\x18\x01 \x01(\v2\x13.test.v1.RecursiveBR\x01b\"/\n" +
	"\n" +
	"RecursiveB\x12!\n" +
	"\x01a\x18\x01 \x01(\v2\x13.test.v1.RecursiveAR\x01a*b\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03B;Z9github.com/yurasolovjov/protodefault/proto/test/v1;testv1b\x06proto3"

var (
	file_test_v1_test_messages_proto_rawDescOnce sync.Once
	file_test_v1_test_messages_proto_rawDescData []byte
)

func file_test_v1_test_messages_proto_rawDescGZIP() []byte {
	file_test_v1_test_messages_proto_rawDescOnce.Do(func() {
		file_test_v1_test_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_v1_test_messages_proto_rawDesc), len(file_test_v1_test_messages_proto_rawDesc)))
	})
	return file_test_v1_test_messages_proto_rawDescData
}

var file_test_v1_test_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_v1_test_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_test_v1_test_messages_proto_goTypes = []any{
	(LogLevel)(0),                 // 0: test.v1.LogLevel
	(*FeatureFlag)(nil),           // 1: test.v1.FeatureFlag
	(*TestMessage)(nil),           // 2: test.v1.TestMessage
	(*OneofConflict)(nil),         // 3: test.v1.OneofConflict
	(*RecursiveA)(nil),            // 4: test.v1.RecursiveA
	(*RecursiveB)(nil),            // 5: test.v1.RecursiveB
	nil,                           // 6: test.v1.TestMessage.StringToIntEntry
	nil,                           // 7: test.v1.TestMessage.StringToMsgEntry
	(*durationpb.Duration)(nil),   // 8: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 10: google.protobuf.Struct
	(*structpb.ListValue)(nil),    // 11: google.protobuf.ListValue
	(*structpb.Value)(nil),        // 12: google.protobuf.Value
	(*fieldmaskpb.FieldMask)(nil), // 13: google.protobuf.FieldMask
	(*wrapperspb.BoolValue)(nil),  // 14: google.protobuf.BoolValue
}
var file_test_v1_test_messages_proto_depIdxs = []int32{
	0,  // 0: test.v1.TestMessage.level_by_name:type_name -> test.v1.LogLevel
	0,  // 1: test.v1.TestMessage.level_by_number:type_name -> test.v1.LogLevel
	1,  // 2: test.v1.TestMessage.feature:type_name -> test.v1.FeatureFlag
	1,  // 3: test.v1.TestMessage.features:type_name -> test.v1.FeatureFlag
	6,  // 4: test.v1.TestMessage.string_to_int:type_name -> test.v1.TestMessage.StringToIntEntry
	7,  // 5: test.v1.TestMessage.string_to_msg:type_name -> test.v1.TestMessage.StringToMsgEntry
	8,  // 6: test.v1.TestMessage.duration:type_name -> google.protobuf.Duration
	9,  // 7: test.v1.TestMessage.timestamp:type_name -> google.protobuf.Timestamp
	10, // 8: test.v1.TestMessage.struct_field:type_name -> google.protobuf.Struct
	11, // 9: test.v1.TestMessage.list_field:type_name -> google.protobuf.ListValue
	12, // 10: test.v1.TestMessage.value_field:type_name -> google.protobuf.Value
	13, // 11: test.v1.TestMessage.mask_field:type_name -> google.protobuf.FieldMask
	14, // 12: test.v1.TestMessage.bool_wrapper:type_name -> google.protobuf.BoolValue
	5,  // 13: test.v1.RecursiveA.b:type_name -> test.v1.RecursiveB
	4,  // 14: test.v1.RecursiveB.a:type_name -> test.v1.RecursiveA
	1,  // 15: test.v1.TestMessage.StringToMsgEntry.value:type_name -> test.v1.FeatureFlag
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_test_v1_test_messages_proto_init() }
func file_test_v1_test_messages_proto_init() {
	if File_test_v1_test_messages_proto != nil {
		return
	}
	file_test_v1_test_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*TestMessage_ChoiceStr)(nil),
		(*TestMessage_ChoiceInt)(nil),
	}
	file_test_v1_test_messages_proto_msgTypes[2].OneofWrappers = []any{
		(*OneofConflict_A)(nil),
		(*OneofConflict_B)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_v1_test_messages_proto_rawDesc), len(file_test_v1_test_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_v1_test_messages_proto_goTypes,
		DependencyIndexes: file_test_v1_test_messages_proto_depIdxs,
		EnumInfos:         file_test_v1_test_messages_proto_enumTypes,
		MessageInfos:      file_test_v1_test_messages_proto_msgTypes,
	}.Build()
	File_test_v1_test_messages_proto = out.File
	file_test_v1_test_messages_proto_goTypes = nil
	file_test_v1_test_messages_proto_depIdxs = nil
}
